version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: mysql:5.5 
    env_file:
      - .env 
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    restart: always
  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always
    
volumes:
   database:
